#!/bin/bash

#configure programm for star with session
function run_at_computer_start(){
	local program_name=$1
	
	#for each user
	for d in $( ls /home/); do
		#if .config not exist, create for user
		if [ ! -d "$d/.config" ]; then
			mkdir -p /home/$d/.config/
			chown -R $d:$d /home/$d/.config/
		fi
		mkdir -p /home/$d/.config/autostart/
		cp /usr/share/applications/$program_name.desktop /home/$d/.config/autostart/
	done

	echo "Configuration for $program_name start at session start"
	
}
#install dvd
dpkg-reconfigure libdvd-pkg

#add thunderbird at startup
run_at_computer_start thunderbird

#install firefox extention
#ad block plus
mozilla-extension-manager --install --global https://addons.mozilla.org/firefox/downloads/latest/adblock-plus/addon-1865-latest.xpi
rm -r /usr/lib/firefox-addons/extensions/\{d10d0bf8-f5b5-c8b4-a8b2-2b9879e08c5d\}

#install firefox extention
#Fire tray
mozilla-extension-manager --install --global https://addons.mozilla.org/thunderbird/downloads/latest/firetray/platform:2/addon-4868-latest.xpi
rm -f /usr/lib/thunderbird-addons/extensions/{9533f794-00b4-4354-aa15-c2bbda6989f8}.xpi

#configure remote desktop for each user
for login in $( ls /home/); do
	echo "configure magic-package-remote-help for $login"
	mkdir -p /home/$login/.config/autostart/
	cat <<EOF > /home/$login/.config/autostart/magic-package-remote-help-configure.desktop
[Desktop Entry]
Type=Application
Exec=magic-package-desktop-configure
Name=magic-package-desktop-configure
Icon=magic-package-desktop-configure
Comment=Configure magic-package-desktop at start
EOF
done

echo "install done"



