#!/bin/bash
#install skype manualy for bypass repository dependency
apt-get install skype

#configure programm for star with session
function run_at_computer_start(){
	local program_name=$1
	
	#for each user
	for d in $( ls /home/); do
		mkdir -p /home/$d/.config/autostart/
		cat <<EOF > /home/$d/.config/autostart/$program_name.desktop
[Desktop Entry]
Type=Application
Exec=$program_name
Name=$program_name
Icon=$program_name
Comment=$program_name run at start
EOF
	done

	echo "Configuration for $program_name start at session start"
	
}

function configure_preference_thunderbird(){
	local preference_name=$1
	local preference_value=$2

	#for each user
	for d in $( ls /home/); do
		local preference_file=/home/$d/.thunderbird/*.default/prefs.js

		if [ ! -z $(grep "\"$preference_name\"" $preference_file) ]; then
			echo "user_pref(\"$preference_name\", $preference_value);" >> $preference_file
			echo "add thunderbird preference : $preference_name - $preference_value"
		fi
	done
}

#add skype at startup
run_at_computer_start skype
#add thunderbird at startup
run_at_computer_start thunderbird

#install firefox extention
#ad block plus
mozilla-extension-manager --install --global https://addons.mozilla.org/firefox/downloads/latest/adblock-plus/addon-1865-latest.xpi

#install firefox extention
#Fire tray
mozilla-extension-manager --install --global https://addons.mozilla.org/thunderbird/downloads/latest/firetray/platform:2/addon-4868-latest.xpi

configure_preference_thunderbird "extensions.firetray.start_hidden" true

echo "install done"



