#!/bin/bash

if [ ! -f /usr/local/sbin/mozilla-extension-manager ]; then
	wget -O /usr/local/sbin/mozilla-extension-manager https://raw.githubusercontent.com/NicolasBernaerts/ubuntu-scripts/master/mozilla/mozilla-extension-manager
	chmod +x /usr/local/sbin/mozilla-extension-manager
    echo "Tool mozilla-extension-manager installed."
fi

#install partner repository
if ! grep -q "deb http://archive.canonical.com/ubuntu $(lsb_release -sc) partner" /etc/apt/sources.list; then
	add-apt-repository -y -u "deb http://archive.canonical.com/ubuntu $(lsb_release -sc) partner" 
fi

echo "install preparation"
