#!/bin/bash
#install partner for skype
if ! grep -q "deb http://archive.canonical.com/ubuntu $(lsb_release -sc) partner" /etc/apt/sources.list; then
	add-apt-repository "deb http://archive.canonical.com/ubuntu $(lsb_release -sc) partner" 
	echo "Added  partner repository done"
fi

echo "install preparation"
